### ISSUE TITLE
Error on captcha.text

### ISSUE THREAD

**Issue by TheDeadCraftPT** [Shashank3736/captcha-canvas#10]
At the constructor you define this.captcha.characters but then on this.captcha.text you use this.characters to substr so it gives me 32 characters while captcha has only 6.
![image](https://user-images.githubusercontent.com/46866023/92276924-d665ae00-eee9-11ea-9574-1146608f7af5.png)

**Comment by Shashank3736** [comment]
Yeah, it's because of update from v1 -> v2. I forget to change some small typos. This issue will be resolved today. Thx for the info.

For now you can use custom text or captcha.text.substr(0, 6)

**Comment by Shashank3736** [comment]
@all-contributors please add @TheDeadCraftPT for reporting captcha.text bug.
