### ISSUE TITLE
RuntimeError: libfontconfig.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Haruko8958** [Shashank3736/captcha-canvas#33]

**Comment by ZeroDiscord** [comment]
Does this have a nix alternative? I do not have root access to the docker container it's being hosted on.

**Comment by Shashank3736** [comment]
> Does this have a nix alternative? I do not have root access to the docker container it's being hosted on.

As far as I know, no there is no alternative.

**Comment by Shashank3736** [comment]
close because of inactivity
