### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by Wizmoore** [Shashank3736/captcha-canvas#38]
hello iam using Replit and iam getting this error any idea how i can fix it 

there is not Letters on the photo 
Preview https://imgur.com/Pedn0gd

**Comment by Shashank3736** [comment]
Check issue #31 the problem is with skia-canvas, use v2 for now. v2.4.0 (#34) will have all the features of v3 in node-canvas.

**Comment by Wizmoore** [comment]
same problem after i use v2.4.0 
https://prnt.sc/2461xlq
how i can use external font using font path
like this
```js
      const { registerFont } = require('canvas')
       registerFont('./Structures/fonts/Genta.ttf', { family: 'Genta' })
```

**this is my code** 

```js
const captcha = new CaptchaGenerator()

          .setDimension(150, 450)
          .setCaptcha({font: "Genta", size: 60, color: "deeppink" })
          .setDecoy({ opacity: 0.5 })
          .setTrace({ color: "deeppink" });

        const captchaAttachment = captcha.generateSync(
          await captcha.png, 
          "captcha.png"
          );
        interaction.reply({ files: [captchaAttachment], content: `Code: ${captcha.text}` });
```

**Comment by Shashank3736** [comment]
check version correctly. v2.4.0 is not yet released it's still a draft. BTW the way you use registerFont() is correct so the only issue is custom font do not support in your system.

**Comment by Shashank3736** [comment]
Close because of inactivity I am going to assume that problem is resolved.
