### ISSUE TITLE
Specified module could not be found.

### ISSUE THREAD

**Issue by niyuki** [Shashank3736/captcha-canvas#39]
At node v16.9.0 I tried to install captcha-canvas like in the docs (https://www.npmjs.com/package/captcha-canvas) and after downloading captcha-canvas it keeps returning following Error:
![image](https://user-images.githubusercontent.com/75905663/149390523-551d676e-bc7f-4411-a68c-4807e3a8897f.png)
I can't tell if it's the node version or my computer. I tried uninstalling node_modules & deleting package-lock.json and redownloading everything but I couldnt find any solution yet.

**Comment by Shashank3736** [comment]
try installing [`skia-canvas`](https://www.npmjs.com/package/skia-canvas) by command
```
npm i skia-canvas
```
Most probably your system (computer in this case) do not support `skia-canvas`
