### ISSUE TITLE
Displaying undefined on 4 characters

### ISSUE THREAD

**Issue by AshuGuptaGamer** [Shashank3736/captcha-canvas#43]
I tried to set the characters limit to 4 but it displays those 4 characters but also says undefined at the end.
```js
const captcha = new Captcha(100, 100);
captcha.addDecoy().drawTrace().drawCaptcha({ characters: 4 });
```

![image](https://user-images.githubusercontent.com/59139918/179762095-06526aec-7052-485b-8fbc-aefa52d8b365.png)

**Comment by Shashank3736** [comment]
Which version of captcha-canvas you are using right now?

**Comment by AshuGuptaGamer** [comment]
Version: 3.1.0

**Comment by Shashank3736** [comment]
ok, issue is confirmed I will try to solve it today thank you for reporting this. For the time you can use CaptchaGenerator

**Comment by AshuGuptaGamer** [comment]
Okay, for the time being, I will use 6 characters and wait for the bug to be fixed. :)

**Comment by Shashank3736** [comment]
To solve this problem you have to use drawCaptcha before addDecoy and drawTrace. So,

```
// wrong
const captcha = new Captcha(100, 100);
captcha.addDecoy().drawTrace().drawCaptcha({ characters: 4 });
```

```
// right
const captcha = new Captcha(400, 100);
captcha.drawCaptcha({ characters: 4 }).addDecoy().drawTrace();
```

Try this and let me know if you are still facing any problem.

**Comment by Shashank3736** [comment]
New release v3.1.1 will solve your issue.

```js
const captcha = new Captcha(100, 100, 4);
captcha.addDecoy().drawTrace().drawCaptcha();
```

This will create a captcha with 4 characters and also you can draw a captcha above the decoy and trace line.

**Comment by AshuGuptaGamer** [comment]
okay thanks

**Comment by Shashank3736** [comment]
Let me know if your issue is resolved or not. If it is resolved then please close the issue
