### ISSUE TITLE
"MODULE NOT FOUND' captcha-canvas

### ISSUE THREAD

**Issue by NiklasPeterson** [Shashank3736/captcha-canvas#45]
Hey @Shashank3736 ! I'm getting this error when running my project with the captcha-canvas installed:
<img width="1277" alt="Screenshot 2022-08-15 at 1 12 52 AM" src="https://user-images.githubusercontent.com/5664205/184684727-4e58c7a1-5de9-40ba-a930-ba224abf3f0b.png">

It looks like the script file is missing inside the node_modules. I have tried to remove and install several times but doesn't get any different results.

Package.json:
<img width="270" alt="Screenshot 2022-08-15 at 1 12 29 AM" src="https://user-images.githubusercontent.com/5664205/184684835-b536ce63-fcbb-4071-a606-10c609199f52.png">

node_modules:
<img width="135" alt="Screenshot 2022-08-15 at 1 12 43 AM" src="https://user-images.githubusercontent.com/5664205/184684881-addffcc1-b207-49d6-a752-e74d4376cb4e.png">

**Comment by fasterplayer** [comment]
They broked the package but won't reply to issues. Gotta find a work around.

**Comment by Shashank3736** [comment]
> They broked the package but won't reply to issues. Gotta find a work around.

Who broked the package?

**Comment by Shashank3736** [comment]
Update the package the problem will be solved thank you for reporting the issue.

**Comment by NiklasPeterson** [comment]
Perfect works now! Thanks for the fast response and fix!
