### ISSUE TITLE
.setBackground() not working (v2.3.1)

### ISSUE THREAD

**Issue by AstrooKai** [Shashank3736/captcha-canvas#49]
```js
const randomString = require('random-base64-string')
  const filename = randomString(10);
  const { CaptchaGenerator } = require("captcha-canvas");
  const { writeFileSync } = require('fs');
  const captcha = new CaptchaGenerator()
    .setDimension(150, 450) 
    .setCaptcha({size: 60, color: "#bd7a21"})
    .setBackground("./cdn/media/bsd-bg.jpg") //this image path is valid
    .setDecoy({opacity: 0.5})
    .setTrace({color: "#bd7a21"});
  const buffer = captcha.generateSync();
  writeFileSync(`./captcha/${filename}.png`, buffer);
  res.json({text: captcha.text, image: `https://eca-beta.astrookai.repl.co/captcha/${filename}.png`});

//ex: returns {"text":"DEEDDE","image":"https://eca-beta.astrookai.repl.co/captcha/rh5OF1CHuX.png"}
  ```
The code above generates a captcha image, the problem is that the `.setBackground()` doesn't add the image below as the background, is there a reason why this is happening? No errors are logged to the console when the code is executed.

**Supposed background image**
![image](https://user-images.githubusercontent.com/81066723/210219489-c4308f69-a968-4242-9f77-025c19a4d39a.png)
**Actual Result**
![image](https://user-images.githubusercontent.com/81066723/210219741-5de6b941-5105-4a76-b31b-2303b91fae04.png)

**Comment by Shashank3736** [comment]
You are using `generateSync` method to generate image. `generateSync` do not support `setBackground` customization see [here](https://captcha-canvas.js.org/v2/CaptchaGenerator.html#generateSync) in documentation. You have two option:
1. Use `generate` method to generate captcha image.
2. Pass your image through `generateSync` option

```js
const { CaptchaGenerator, resolveImage } = require("captcha-canvas");
const fs = require("fs");
const img = await resolveImage("./path/to/file");

const captcha = new CaptchaGenerator()
.generateSync({background: img});

fs.writeFileSync("image.png", captcha);
```

My personal recommendation is to use method 1.

**Comment by AstrooKai** [comment]
Thank you for the fast response, this has also solved my problem. Though one question came to my mind, is there a way to generate an alphanumeric captcha or does the package supports this feature?

**Comment by Shashank3736** [comment]
You can use `crypto` module to generate an alphanumeric captcha. `crypto` module comes with Node.js, and the package also use it to generate captchas.
```js
// To generate random alphanumeric string
const { randomBytes } = require('crypto'); 
const randomString = randomBytes(10).toString('hex').substring(0, 6);
console.log(randomString); //will log a 6 character string in console
```
