### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by WoWisme** [Shashank3736/captcha-canvas#53]
Hello. I am having a problem using the skia-canvas, and I tried to do the captcha setup on my local host pc, which worked fine, but after trying to set my bot up on a oracle linux server, it gave me new errors. I have no clue why, but it gave me the error: https://sourceb.in/OyEm3YVZkb

I fixed this by reinstalling node_modules, and doing npm install skia-canvas (I also did some other funky commands to fix a error, something to do with libfontconfig). When that was fixed, it worked. I could get my captcha, but all the text had now been made smaller. The letters and numbers before on my local host was normal. A good size that was easy to read, but on the host, it was micro, and hard to see what they were.

Before:
![image](https://user-images.githubusercontent.com/87548278/221057040-6da50e07-298e-48cf-8b77-2a3a551d93ce.png)

After:
![image](https://user-images.githubusercontent.com/87548278/221057004-ebdea0c8-09c3-4a0e-affb-f17e25822215.png)

I am not so used to GitHub, so I may not see any given message. So if you are able to help with the issue, please do try and contact me on discord: WoW#4929

**Comment by Shashank3736** [comment]
You can change the font size by using [setCaptcha](https://captcha-canvas.js.org/CaptchaGenerator.html#setCaptcha) method in `CaptchaGenerator` or [drawCaptcha](https://captcha-canvas.js.org/Captcha.html#drawCaptcha) method in `Captcha` class. Try using these options.

**Comment by WoWisme** [comment]
I tried doing that with drawCaptcha, but I feel like I don't understand how to do it correctly, cause each method I try, doesn't work. I looked through each docs, and I am using the latest of the captcha-canvas with the latest of skia-canvas, and it just change after adding skia-canvas. I even tried looking through the docs of skia-canvas, but didn't find anything there for it to change my font size. I had a look after the libfontconfig, which I have no clue where is installed, so I can't have a look at that, but if you have an example to how I use the drawCaptcha in Captcha, to change the font, that would be nice

**Comment by WoWisme** [comment]
In this image, I have shown you to sorts of code. The first embed with the code size 40, and the second being size 60.
![image](https://user-images.githubusercontent.com/87548278/221168323-3cb2cdb5-7e9e-449b-a4f9-77643c009628.png)

The exact same size, and I just changed as it is in the docs.
code:
Size 40: https://sourceb.in/CRr5xQN5Dk
Size 60: https://sourceb.in/FMK1nHfgL5

**Comment by Shashank3736** [comment]
hmm! weird. Try using `v2.3.1` it works with `canvas` module so it may solve your issue.

**Comment by WoWisme** [comment]
https://sourceb.in/FMK1nHfgL5 
This was the code. The captcha generate was at the top from line 13-26

**Comment by Shashank3736** [comment]
Provide me info related to your os and node version

**Comment by Shashank3736** [comment]
Close due to inactivity.
