### ISSUE TITLE
Cannot find module 'XXX/../package.json'

### ISSUE THREAD

**Issue by webrsb** [Shashank3736/captcha-canvas#61]
I try to bundle with webpack and show this error:
```
uncaught Error Error: Cannot find module 'XXX/../package.json'
    at webpackEmptyContext (XXX\main.js:71350:10)
    at eval (repl:1:26)
```
It seen webpack don't bundle directory.
https://github.com/Shashank3736/captcha-canvas/blob/1f95ac7bf34fc1574702281859a1365efcd03f2e/ts-script/index.ts#L7
Is it really needed?
Thanks.

**Comment by Shashank3736** [comment]
Nope it's not needed I just added this at the start of the project to allow people access to the version of captcha module they are using. Thank you for reporting this.

**Comment by Shashank3736** [comment]
Removed the version const from the module now... in `v3.2.2`
